# Code Generated by Sidekick is for learning and experimentation purposes only.
import requests

def test_sfmc_auth():
    # URL of the Flask application running locally
    url = "http://127.0.0.1:5000/sfmc-auth"

    try:
        # Make a GET request to the /sfmc-auth endpoint
        response = requests.get(url)
        response.raise_for_status()

        # Parse the JSON response
        data = response.json()

        # Check if the access token is present in the response
        if "access_token" in data:
            print("✅ SFMC Authentication Successful!")
            print(f"Access Token: {data['access_token']}")
        else:
            print("⚠️ SFMC Authentication Failed!")
            print(f"Error: {data.get('error', 'Unknown error')}")

    except requests.exceptions.RequestException as e:
        print(f"⚠️ Error during request: {e}")

# Run the test function
if __name__ == "__main__":
    test_sfmc_auth()
